spring:
  datasource:
    username: admin
    password: admin
    url: jdbc:postgresql://localhost:5432/user
  jpa:
    show-sql: true
    spring.jpa.database-platform: org.postgresql.Driver
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
      client:
        registration:
          awuser-client:
            provider: authblog
            client-id: awuser
            client-secret: 123456
            authorization-grant-type: client_credentials
            scope: users:read
            client-name: awuser-client
        provider:
          authblog:
            issuer-uri: http://localhost:8082

server:
  port: 8081
  
aw:
  user-api:
    url: 'http://localhost:8080'
    encoded-credentials: 'YWRtaW5AZW1haWwuY29tOmFkbWlu'



